/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CandidateId = bigint;
export interface CandidateProfile {
  'bio' : string,
  'profileId' : CandidateId,
  'fullName' : string,
  'email' : string,
  'timestamp' : Timestamp,
  'preferredRoleType' : RoleType,
  'cvLink' : string,
  'skills' : Array<string>,
}
export interface JobPosting {
  'roleType' : RoleType,
  'jobDescription' : string,
  'jobTitle' : string,
  'timestamp' : Timestamp,
  'contactEmail' : string,
  'companyName' : string,
  'requiredSkills' : Array<string>,
  'postingId' : JobPostingId,
}
export type JobPostingId = bigint;
export type PortalRole = { 'employer' : null } |
  { 'jobSeeker' : null };
export type RoleType = { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export type SessionToken = string;
export type Timestamp = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhitelistEntry {
  'note' : string,
  'email' : string,
  'addedAt' : Timestamp,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmailToWhitelist' : ActorMethod<[string, string], undefined>,
  'addPortalUser' : ActorMethod<[string, string, PortalRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePortalUserPassword' : ActorMethod<[string, string], undefined>,
  'getAllCandidateProfiles' : ActorMethod<[], Array<CandidateProfile>>,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateProfileCount' : ActorMethod<[], bigint>,
  'getJobPostingCount' : ActorMethod<[], bigint>,
  'getPortalSession' : ActorMethod<
    [SessionToken],
    [] | [{ 'portalRole' : PortalRole, 'username' : string }]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmailWhitelisted' : ActorMethod<[string], boolean>,
  'listEmailWhitelist' : ActorMethod<[], Array<WhitelistEntry>>,
  'listPortalUsers' : ActorMethod<
    [],
    Array<{ 'portalRole' : PortalRole, 'username' : string }>
  >,
  'loginPortalUser' : ActorMethod<[string, string], SessionToken>,
  'logoutPortalUser' : ActorMethod<[SessionToken], undefined>,
  'registerCandidateProfile' : ActorMethod<
    [string, string, Array<string>, RoleType, string, string],
    CandidateId
  >,
  'removeEmailFromWhitelist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitJobPosting' : ActorMethod<
    [string, string, RoleType, Array<string>, string, string],
    JobPostingId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];