/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PortalRole = IDL.Variant({
  'employer' : IDL.Null,
  'jobSeeker' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoCallId = IDL.Nat;
export const IVideoCallStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const IVideoCall = IDL.Record({
  'status' : IVideoCallStatus,
  'invitedUser' : IDL.Text,
  'createdAt' : Timestamp,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
  'callId' : VideoCallId,
  'scheduledAt' : Timestamp,
  'scheduledBy' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CandidateId = IDL.Nat;
export const RoleType = IDL.Variant({
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const CandidateProfile = IDL.Record({
  'bio' : IDL.Text,
  'profileId' : CandidateId,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Timestamp,
  'preferredRoleType' : RoleType,
  'cvLink' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const JobPostingId = IDL.Nat;
export const JobPosting = IDL.Record({
  'roleType' : RoleType,
  'jobDescription' : IDL.Text,
  'jobTitle' : IDL.Text,
  'timestamp' : Timestamp,
  'contactEmail' : IDL.Text,
  'companyName' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'postingId' : JobPostingId,
});
export const SessionToken = IDL.Text;
export const WhitelistEntry = IDL.Record({
  'note' : IDL.Text,
  'email' : IDL.Text,
  'addedAt' : Timestamp,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmailToWhitelist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPortalUser' : IDL.Func([IDL.Text, IDL.Text, PortalRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelVideoCall' : IDL.Func([VideoCallId], [], []),
  'changePortalUserPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'confirmVideoCall' : IDL.Func([VideoCallId], [], []),
  'findCallsForUser' : IDL.Func([IDL.Text], [IDL.Vec(IVideoCall)], ['query']),
  'findUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getAllCandidateProfiles' : IDL.Func(
      [],
      [IDL.Vec(CandidateProfile)],
      ['query'],
    ),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getJobPostingCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMonthlyCompletedProfiles' : IDL.Func([], [IDL.Nat], ['query']),
  'getPortalSession' : IDL.Func(
      [SessionToken],
      [
        IDL.Opt(
          IDL.Record({ 'portalRole' : PortalRole, 'username' : IDL.Text })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoCallDetails' : IDL.Func(
      [VideoCallId],
      [IDL.Opt(IVideoCall)],
      ['query'],
    ),
  'getVideoCallsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementMonthlyCompletedProfiles' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmailWhitelisted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listEmailWhitelist' : IDL.Func([], [IDL.Vec(WhitelistEntry)], []),
  'listPortalUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({ 'portalRole' : PortalRole, 'username' : IDL.Text })
        ),
      ],
      [],
    ),
  'loginPortalUser' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], []),
  'logoutPortalUser' : IDL.Func([SessionToken], [], []),
  'registerCandidateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), RoleType, IDL.Text, IDL.Text],
      [CandidateId],
      [],
    ),
  'removeEmailFromWhitelist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleVideoCall' : IDL.Func(
      [IDL.Text, Timestamp, IDL.Nat, IDL.Text],
      [VideoCallId],
      [],
    ),
  'submitJobPosting' : IDL.Func(
      [IDL.Text, IDL.Text, RoleType, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [JobPostingId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PortalRole = IDL.Variant({
    'employer' : IDL.Null,
    'jobSeeker' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoCallId = IDL.Nat;
  const IVideoCallStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const IVideoCall = IDL.Record({
    'status' : IVideoCallStatus,
    'invitedUser' : IDL.Text,
    'createdAt' : Timestamp,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
    'callId' : VideoCallId,
    'scheduledAt' : Timestamp,
    'scheduledBy' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const CandidateId = IDL.Nat;
  const RoleType = IDL.Variant({
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const CandidateProfile = IDL.Record({
    'bio' : IDL.Text,
    'profileId' : CandidateId,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Timestamp,
    'preferredRoleType' : RoleType,
    'cvLink' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const JobPostingId = IDL.Nat;
  const JobPosting = IDL.Record({
    'roleType' : RoleType,
    'jobDescription' : IDL.Text,
    'jobTitle' : IDL.Text,
    'timestamp' : Timestamp,
    'contactEmail' : IDL.Text,
    'companyName' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'postingId' : JobPostingId,
  });
  const SessionToken = IDL.Text;
  const WhitelistEntry = IDL.Record({
    'note' : IDL.Text,
    'email' : IDL.Text,
    'addedAt' : Timestamp,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmailToWhitelist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPortalUser' : IDL.Func([IDL.Text, IDL.Text, PortalRole], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelVideoCall' : IDL.Func([VideoCallId], [], []),
    'changePortalUserPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'confirmVideoCall' : IDL.Func([VideoCallId], [], []),
    'findCallsForUser' : IDL.Func([IDL.Text], [IDL.Vec(IVideoCall)], ['query']),
    'findUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getAllCandidateProfiles' : IDL.Func(
        [],
        [IDL.Vec(CandidateProfile)],
        ['query'],
      ),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getJobPostingCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMonthlyCompletedProfiles' : IDL.Func([], [IDL.Nat], ['query']),
    'getPortalSession' : IDL.Func(
        [SessionToken],
        [
          IDL.Opt(
            IDL.Record({ 'portalRole' : PortalRole, 'username' : IDL.Text })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoCallDetails' : IDL.Func(
        [VideoCallId],
        [IDL.Opt(IVideoCall)],
        ['query'],
      ),
    'getVideoCallsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementMonthlyCompletedProfiles' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmailWhitelisted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listEmailWhitelist' : IDL.Func([], [IDL.Vec(WhitelistEntry)], []),
    'listPortalUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({ 'portalRole' : PortalRole, 'username' : IDL.Text })
          ),
        ],
        [],
      ),
    'loginPortalUser' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], []),
    'logoutPortalUser' : IDL.Func([SessionToken], [], []),
    'registerCandidateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), RoleType, IDL.Text, IDL.Text],
        [CandidateId],
        [],
      ),
    'removeEmailFromWhitelist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleVideoCall' : IDL.Func(
        [IDL.Text, Timestamp, IDL.Nat, IDL.Text],
        [VideoCallId],
        [],
      ),
    'submitJobPosting' : IDL.Func(
        [IDL.Text, IDL.Text, RoleType, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [JobPostingId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };