/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CandidateId = bigint;
export interface WhitelistEntry {
    note: string;
    email: string;
    addedAt: Timestamp;
}
export type Timestamp = bigint;
export type SessionToken = string;
export type JobPostingId = bigint;
export interface JobPosting {
    roleType: RoleType;
    jobDescription: string;
    jobTitle: string;
    timestamp: Timestamp;
    contactEmail: string;
    companyName: string;
    requiredSkills: Array<string>;
    postingId: JobPostingId;
}
export interface CandidateProfile {
    bio: string;
    profileId: CandidateId;
    fullName: string;
    email: string;
    timestamp: Timestamp;
    preferredRoleType: RoleType;
    cvLink: string;
    skills: Array<string>;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum PortalRole {
    employer = "employer",
    jobSeeker = "jobSeeker"
}
export enum RoleType {
    contract = "contract",
    partTime = "partTime",
    fullTime = "fullTime"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEmailToWhitelist(email: string, note: string): Promise<void>;
    addPortalUser(username: string, passwordHash: string, portalRole: PortalRole): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changePortalUserPassword(username: string, newPasswordHash: string): Promise<void>;
    getAllCandidateProfiles(): Promise<Array<CandidateProfile>>;
    getAllJobPostings(): Promise<Array<JobPosting>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidateProfileCount(): Promise<bigint>;
    getJobPostingCount(): Promise<bigint>;
    getPortalSession(token: SessionToken): Promise<{
        portalRole: PortalRole;
        username: string;
    } | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isEmailWhitelisted(email: string): Promise<boolean>;
    listEmailWhitelist(): Promise<Array<WhitelistEntry>>;
    listPortalUsers(): Promise<Array<{
        portalRole: PortalRole;
        username: string;
    }>>;
    loginPortalUser(username: string, passwordHash: string): Promise<SessionToken>;
    logoutPortalUser(token: SessionToken): Promise<void>;
    registerCandidateProfile(fullName: string, email: string, skills: Array<string>, preferredRoleType: RoleType, cvLink: string, bio: string): Promise<CandidateId>;
    removeEmailFromWhitelist(email: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitJobPosting(companyName: string, jobTitle: string, roleType: RoleType, requiredSkills: Array<string>, jobDescription: string, contactEmail: string): Promise<JobPostingId>;
}
import type { CandidateId as _CandidateId, CandidateProfile as _CandidateProfile, JobPosting as _JobPosting, JobPostingId as _JobPostingId, PortalRole as _PortalRole, RoleType as _RoleType, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEmailToWhitelist(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmailToWhitelist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmailToWhitelist(arg0, arg1);
            return result;
        }
    }
    async addPortalUser(arg0: string, arg1: string, arg2: PortalRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortalUser(arg0, arg1, to_candid_PortalRole_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortalUser(arg0, arg1, to_candid_PortalRole_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changePortalUserPassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changePortalUserPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePortalUserPassword(arg0, arg1);
            return result;
        }
    }
    async getAllCandidateProfiles(): Promise<Array<CandidateProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCandidateProfiles();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCandidateProfiles();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobPostings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobPostings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidateProfileCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidateProfileCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidateProfileCount();
            return result;
        }
    }
    async getJobPostingCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPostingCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPostingCount();
            return result;
        }
    }
    async getPortalSession(arg0: SessionToken): Promise<{
        portalRole: PortalRole;
        username: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortalSession(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortalSession(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEmailWhitelisted(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEmailWhitelisted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEmailWhitelisted(arg0);
            return result;
        }
    }
    async listEmailWhitelist(): Promise<Array<WhitelistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmailWhitelist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmailWhitelist();
            return result;
        }
    }
    async listPortalUsers(): Promise<Array<{
        portalRole: PortalRole;
        username: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPortalUsers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPortalUsers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginPortalUser(arg0: string, arg1: string): Promise<SessionToken> {
        if (this.processError) {
            try {
                const result = await this.actor.loginPortalUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginPortalUser(arg0, arg1);
            return result;
        }
    }
    async logoutPortalUser(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutPortalUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutPortalUser(arg0);
            return result;
        }
    }
    async registerCandidateProfile(arg0: string, arg1: string, arg2: Array<string>, arg3: RoleType, arg4: string, arg5: string): Promise<CandidateId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCandidateProfile(arg0, arg1, arg2, to_candid_RoleType_n21(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCandidateProfile(arg0, arg1, arg2, to_candid_RoleType_n21(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async removeEmailFromWhitelist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEmailFromWhitelist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEmailFromWhitelist(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitJobPosting(arg0: string, arg1: string, arg2: RoleType, arg3: Array<string>, arg4: string, arg5: string): Promise<JobPostingId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitJobPosting(arg0, arg1, to_candid_RoleType_n21(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitJobPosting(arg0, arg1, to_candid_RoleType_n21(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_CandidateProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CandidateProfile): CandidateProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_JobPosting_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPosting): JobPosting {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PortalRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortalRole): PortalRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RoleType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoleType): RoleType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        portalRole: _PortalRole;
        username: string;
    }]): {
    portalRole: PortalRole;
    username: string;
} | null {
    return value.length === 0 ? null : from_candid_record_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roleType: _RoleType;
    jobDescription: string;
    jobTitle: string;
    timestamp: _Timestamp;
    contactEmail: string;
    companyName: string;
    requiredSkills: Array<string>;
    postingId: _JobPostingId;
}): {
    roleType: RoleType;
    jobDescription: string;
    jobTitle: string;
    timestamp: Timestamp;
    contactEmail: string;
    companyName: string;
    requiredSkills: Array<string>;
    postingId: JobPostingId;
} {
    return {
        roleType: from_candid_RoleType_n8(_uploadFile, _downloadFile, value.roleType),
        jobDescription: value.jobDescription,
        jobTitle: value.jobTitle,
        timestamp: value.timestamp,
        contactEmail: value.contactEmail,
        companyName: value.companyName,
        requiredSkills: value.requiredSkills,
        postingId: value.postingId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portalRole: _PortalRole;
    username: string;
}): {
    portalRole: PortalRole;
    username: string;
} {
    return {
        portalRole: from_candid_PortalRole_n18(_uploadFile, _downloadFile, value.portalRole),
        username: value.username
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    profileId: _CandidateId;
    fullName: string;
    email: string;
    timestamp: _Timestamp;
    preferredRoleType: _RoleType;
    cvLink: string;
    skills: Array<string>;
}): {
    bio: string;
    profileId: CandidateId;
    fullName: string;
    email: string;
    timestamp: Timestamp;
    preferredRoleType: RoleType;
    cvLink: string;
    skills: Array<string>;
} {
    return {
        bio: value.bio,
        profileId: value.profileId,
        fullName: value.fullName,
        email: value.email,
        timestamp: value.timestamp,
        preferredRoleType: from_candid_RoleType_n8(_uploadFile, _downloadFile, value.preferredRoleType),
        cvLink: value.cvLink,
        skills: value.skills
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    employer: null;
} | {
    jobSeeker: null;
}): PortalRole {
    return "employer" in value ? PortalRole.employer : "jobSeeker" in value ? PortalRole.jobSeeker : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
}): RoleType {
    return "contract" in value ? RoleType.contract : "partTime" in value ? RoleType.partTime : "fullTime" in value ? RoleType.fullTime : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPosting>): Array<JobPosting> {
    return value.map((x)=>from_candid_JobPosting_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    portalRole: _PortalRole;
    username: string;
}>): Array<{
    portalRole: PortalRole;
    username: string;
}> {
    return value.map((x)=>from_candid_record_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CandidateProfile>): Array<CandidateProfile> {
    return value.map((x)=>from_candid_CandidateProfile_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PortalRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortalRole): _PortalRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RoleType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoleType): _RoleType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortalRole): {
    employer: null;
} | {
    jobSeeker: null;
} {
    return value == PortalRole.employer ? {
        employer: null
    } : value == PortalRole.jobSeeker ? {
        jobSeeker: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoleType): {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} {
    return value == RoleType.contract ? {
        contract: null
    } : value == RoleType.partTime ? {
        partTime: null
    } : value == RoleType.fullTime ? {
        fullTime: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
